// The optional offline code dictionary: human names for clinical codes whose
// events arrived without a display and which the vault itself never names (see
// code-names.ts for the in-vault index this layers behind). Opt-in — nothing is
// fetched or stored until the user turns it on in Settings.
//
// Privacy: the dictionaries are versioned JSON served wholesale from the app's
// OWN origin (`/dict/…`, generated by scripts/build-code-dictionary). There is
// never a per-code or third-party lookup — a network request that revealed
// which codes a vault holds is exactly what this design refuses. Once
// downloaded the maps live in IndexedDB and resolve entirely offline.
//
// Lookup order at render time: an event's own `display` -> the vault-memory
// index (code-names.ts) -> THIS dictionary -> the raw "LOINC 39156-5" fallback.
//
// A plain `svelte/store` (not a `.svelte.ts` rune module), same rationale as
// sync.ts: `writable` is a normal function, so this module and its tests run
// under plain vitest without the Svelte compiler.
import { writable } from 'svelte/store'
import { getAll, put, del, get, clear } from './db'

/** A terminology system's `{ "<code>": "<name>" }` map, as served and stored. */
export type CodeMap = Record<string, string>

export interface ManifestFile {
  system: string
  path: string
  bytes: number
  sha256: string
  entries: number
  label: string
  attribution: string
  starter?: boolean
}

export interface DictManifest {
  version: string
  generated_at: string
  files: ManifestFile[]
}

/** One stored row per system: the manifest metadata plus that system's map. */
interface DictRow extends ManifestFile {
  version: string
  entriesMap: CodeMap
}

const STORE = 'dictionary'
const ENABLED_PREF = 'dict-enabled'
const MANIFEST_PREF = 'dict-manifest'
const MANIFEST_URL = '/dict/manifest.json'

function fileUrl(path: string): string {
  return `/dict/${path}`
}

// --- status surface (read by Settings.svelte via `$dictionaryStatus`) ---

export interface DictionaryStatus {
  enabled: boolean
  /** Downloaded manifest version, or null when nothing is stored. */
  version: string | null
  entryCount: number
  /** Attribution + counts for the muted lines under the Settings toggle;
   * sourced from the stored manifest so they show offline. */
  files: { label: string; entries: number; attribution: string; starter?: boolean }[]
  downloading: boolean
  /** Files completed / total during an in-flight download. */
  progress: { done: number; total: number } | null
  error: string | null
}

const EMPTY_STATUS: DictionaryStatus = {
  enabled: false,
  version: null,
  entryCount: 0,
  files: [],
  downloading: false,
  progress: null,
  error: null,
}

export const dictionaryStatus = writable<DictionaryStatus>({ ...EMPTY_STATUS })

// --- hydrated lookup index (module-level cache) ---
//
// buildTimeline/buildSummary run this on every derivation, so the merged Map is
// built once per session and reused; download/remove invalidate it. Kept as one
// flat `${system}|${code}` -> name Map (the same key code-names.ts uses) so a
// lookup is a single O(1) get regardless of how many systems are loaded.

let cachedIndex: Map<string, string> | null = null

export function invalidateDictionaryCache(): void {
  cachedIndex = null
}

/** The merged dictionary index, or an empty Map when the feature is off or
 * nothing is downloaded. Cached for the session; call after unlock and pass the
 * result into buildTimeline/buildSummary. */
export async function loadDictionaryIndex(): Promise<Map<string, string>> {
  if (cachedIndex) return cachedIndex
  const index = new Map<string, string>()
  if (await isEnabled()) {
    const rows = await getAll<DictRow>(STORE)
    for (const row of rows) {
      for (const code in row.entriesMap) index.set(`${row.system}|${code}`, row.entriesMap[code])
    }
  }
  cachedIndex = index
  return index
}

// --- enable / status helpers ---

export async function isEnabled(): Promise<boolean> {
  return (await get<boolean>('prefs', ENABLED_PREF)) === true
}

/** Rebuild the status store from what's in IndexedDB. Call on mount so Settings
 * reflects a dictionary downloaded in an earlier session. */
export async function refreshDictionaryStatus(): Promise<void> {
  const enabled = await isEnabled()
  const manifest = await get<DictManifest>('prefs', MANIFEST_PREF)
  if (!enabled || !manifest) {
    dictionaryStatus.set({ ...EMPTY_STATUS, enabled })
    return
  }
  dictionaryStatus.set({
    enabled: true,
    version: manifest.version,
    entryCount: manifest.files.reduce((n, f) => n + f.entries, 0),
    files: manifest.files.map((f) => ({
      label: f.label,
      entries: f.entries,
      attribution: f.attribution,
      ...(f.starter ? { starter: true } : {}),
    })),
    downloading: false,
    progress: null,
    error: null,
  })
}

// --- manifest / download / remove ---

export async function fetchManifest(): Promise<DictManifest> {
  const res = await fetch(MANIFEST_URL, { cache: 'no-store' })
  if (!res.ok) throw new Error(`dictionary manifest: HTTP ${res.status}`)
  return (await res.json()) as DictManifest
}

/** Total download size (bytes) across all files — shown before the user
 * commits to downloading. */
export function manifestBytes(manifest: DictManifest): number {
  return manifest.files.reduce((n, f) => n + f.bytes, 0)
}

/** Fetch every dictionary file wholesale, store each system's map, and mark the
 * feature enabled. Idempotent — re-running replaces the stored rows, which is
 * also how an update is applied. */
export async function downloadDictionary(manifest?: DictManifest): Promise<void> {
  const m = manifest ?? (await fetchManifest())
  dictionaryStatus.update((s) => ({
    ...s,
    downloading: true,
    error: null,
    progress: { done: 0, total: m.files.length },
  }))
  try {
    let done = 0
    for (const file of m.files) {
      const res = await fetch(fileUrl(file.path), { cache: 'no-store' })
      if (!res.ok) throw new Error(`${file.label}: HTTP ${res.status}`)
      const entriesMap = (await res.json()) as CodeMap
      const row: DictRow = { ...file, version: m.version, entriesMap }
      await put(STORE, row)
      done++
      dictionaryStatus.update((s) => ({ ...s, progress: { done, total: m.files.length } }))
    }
    await put('prefs', m, MANIFEST_PREF)
    await put('prefs', true, ENABLED_PREF)
    invalidateDictionaryCache()
    await refreshDictionaryStatus()
  } catch (err) {
    dictionaryStatus.update((s) => ({
      ...s,
      downloading: false,
      progress: null,
      error: err instanceof Error ? err.message : 'Download failed.',
    }))
    throw err
  }
}

/** Delete the downloaded dictionaries and turn the feature off. */
export async function removeDictionary(): Promise<void> {
  await clear(STORE)
  await del('prefs', ENABLED_PREF)
  await del('prefs', MANIFEST_PREF)
  invalidateDictionaryCache()
  await refreshDictionaryStatus()
}

/** A YYYY-MM-DD manifest version compares lexicographically, so a plain `>`
 * is a date comparison. */
export function isNewerVersion(candidate: string, current: string): boolean {
  return candidate > current
}

export interface UpdateCheck {
  current: string | null
  latest: string
  updateAvailable: boolean
}

/** Compare the live manifest against what's stored. Does not download. */
export async function checkForUpdate(): Promise<UpdateCheck> {
  const manifest = await fetchManifest()
  const stored = await get<DictManifest>('prefs', MANIFEST_PREF)
  const current = stored?.version ?? null
  return {
    current,
    latest: manifest.version,
    updateAvailable: current === null || isNewerVersion(manifest.version, current),
  }
}
